export const SETUP = 'SETUP';
export const SELECT_CONTRACT = "SELECT_ID";
export const UPDATE_FIRST_NAME = "UPDATE_FIRST_NAME";
export const UPDATE_LAST_NAME = "UPDATE_LAST_NAME";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_PHONE_NO = "UPDATE_PHONE_NO";
export const UPDATE_INTO_CONTRACT_LIST = "UPDATE_INTO_CONTRACT_LIST";
export const RESET_CONTRACT = "RESET_CONTRACT";